import type { Post } from './types'

export function getSeedPosts(neighborhood: string): Partial<Post>[] {
  return [
    {
      id: `seed-1-${neighborhood}`,
      type: 'tarvitsen',
      title: 'Onko kellään porakonetta lainattavaksi?',
      description: 'Pitäisi porata muutama reikä seinään. Palautan saman päivän aikana!',
      location: neighborhood,
      is_pro_listing: false,
      like_count: 3,
      comment_count: 1,
      tags: ['tyokalut'],
      created_at: new Date(Date.now() - 3600000).toISOString(),
      updated_at: new Date(Date.now() - 3600000).toISOString(),
      is_active: true,
      is_seed: true,
      user: {
        id: 'seed-user-1',
        name: 'Mikko K.',
        avatar_url: null,
        naapurusto: neighborhood,
      } as any,
    },
    {
      id: `seed-2-${neighborhood}`,
      type: 'tarjoan',
      title: 'Vapaaehtoinen koiranulkoiluttaja',
      description: 'Tykkään ulkoilla koirien kanssa. Voin auttaa arkisin klo 10-14.',
      location: neighborhood,
      is_pro_listing: false,
      like_count: 5,
      comment_count: 2,
      tags: ['lemmikit'],
      created_at: new Date(Date.now() - 7200000).toISOString(),
      updated_at: new Date(Date.now() - 7200000).toISOString(),
      is_active: true,
      is_seed: true,
      user: {
        id: 'seed-user-2',
        name: 'Anna L.',
        avatar_url: null,
        naapurusto: neighborhood,
      } as any,
    },
    {
      id: `seed-3-${neighborhood}`,
      type: 'ilmaista',
      title: 'Sohva hyvässä kunnossa',
      description: 'Harmaa 3-istuttava sohva, pitää noutaa tänään tai huomenna. Muutan pois.',
      location: neighborhood,
      is_pro_listing: false,
      like_count: 8,
      comment_count: 4,
      tags: ['huonekalut'],
      created_at: new Date(Date.now() - 10800000).toISOString(),
      updated_at: new Date(Date.now() - 10800000).toISOString(),
      is_active: true,
      is_seed: true,
      user: {
        id: 'seed-user-3',
        name: 'Jari M.',
        avatar_url: null,
        naapurusto: neighborhood,
      } as any,
    },
    {
      id: `seed-4-${neighborhood}`,
      type: 'nappaa',
      title: 'Tuoreita korvapuusteja',
      description: 'Leivoin liikaa! 12 korvapuustia jakoon, nouda Fleminginkadulta.',
      location: neighborhood,
      is_pro_listing: false,
      like_count: 12,
      comment_count: 6,
      tags: ['ruoka'],
      expires_at: new Date(Date.now() + 43200000).toISOString(),
      created_at: new Date(Date.now() - 1800000).toISOString(),
      updated_at: new Date(Date.now() - 1800000).toISOString(),
      is_active: true,
      is_seed: true,
      user: {
        id: 'seed-user-4',
        name: 'Liisa H.',
        avatar_url: null,
        naapurusto: neighborhood,
      } as any,
    },
    {
      id: `seed-5-${neighborhood}`,
      type: 'lainaa',
      title: 'Lainaan painepesuria',
      description: 'Kärcher K5, päivävuokra 5€. Sopii terassin, auton tai pyörän pesuun.',
      location: neighborhood,
      daily_fee: 5,
      is_pro_listing: false,
      like_count: 2,
      comment_count: 0,
      tags: ['tyokalut'],
      created_at: new Date(Date.now() - 86400000).toISOString(),
      updated_at: new Date(Date.now() - 86400000).toISOString(),
      is_active: true,
      is_seed: true,
      user: {
        id: 'seed-user-5',
        name: 'Timo P.',
        avatar_url: null,
        naapurusto: neighborhood,
      } as any,
    },
  ]
}
