/* global */
// Realistinen suomi-feed — Kallio/Sörnäinen, oikeita katunimiä, mietittyjä otsikoita.
// Kuvat tulevat sekoituksesta Unsplash-fotoja eri valotuksilla; treat them
// with a uniform CSS filter on render to make them feel curated, not generic.

const POSTS_V3 = [
  {
    id: "p1", type: "tarjoan",
    title: "Moccamaster KBG741 — toimii vielä mainiosti",
    body: "Vaihdoin uuteen, tämä saa hyvän kodin. Mukana cone-suodattimia ehkä 50 kpl. Nouto Vaasankadulta arkisin klo 17 jälkeen tai viikonloppuisin.",
    author: "Anni K.", authorFull: "Anni Korhonen",
    address: "Vaasankatu 14", neighborhood: "Kallio",
    time: "12 min", precise: "klo 14:32",
    avatar: "https://i.pravatar.cc/120?img=49",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&q=85&auto=format",
    price: "40 €",
    likes: 18, saves: 7,
    distance: "120 m",
    online: true, verified: true,
  },
  {
    id: "p2", type: "tarvitsen",
    title: "Etsin auttajaa muuttoon lauantaina (3. krs, ei hissiä)",
    body: "Iso sohva ja kaappi, loput pikku. Maksan 15€/h ja saa mehua. Sörkästä Pasilaan, pakettiauto on jo varattu klo 10–14.",
    author: "Mikko V.", authorFull: "Mikko Virtanen",
    address: "Helsinginkatu 27", neighborhood: "Kallio",
    time: "32 min", precise: "klo 14:12",
    avatar: "https://i.pravatar.cc/120?img=12",
    urgent: true,
    likes: 4,
    distance: "340 m",
    online: false, verified: true,
  },
  {
    id: "p3", type: "lainaa",
    title: "Bosch Professional 18V akkuporakone",
    body: "Mukana 2 akkua + laturi + kärkikasetti. Käytetty kotiremonttiin viime kesänä, hyvässä kunnossa.",
    author: "Tuomas L.", authorFull: "Tuomas Lehtinen",
    address: "Sturenkatu 21", neighborhood: "Vallila",
    time: "1 t", precise: "klo 13:30",
    avatar: "https://i.pravatar.cc/120?img=33",
    image: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=900&q=85&auto=format",
    price: "5 € / pv",
    deposit: "30 € vakuus",
    likes: 11, saves: 4,
    distance: "800 m",
    online: true, verified: true,
    rating: 4.9, reviews: 28, responseTime: "~12 min",
  },
  {
    id: "p4", type: "tapahtuma",
    title: "Brahenkentän kevätsiivous & kahvit",
    body: "Kallio-seura järjestää siivouspäivän — pussit, hanskat ja kahvi tarjotaan. Tervetuloa kaikki!",
    author: "Kallio-seura", authorFull: "Kallio-seura ry",
    address: "Brahenkenttä", neighborhood: "Kallio",
    eventDate: "LA 4.5.",
    eventTime: "11:00 – 14:00",
    time: "2 t",
    avatar: null,
    attending: 24, capacity: 60,
    distance: "550 m",
    organizer: true,
  },
  {
    id: "p5", type: "ilmaista",
    title: "Lasten talvitakki, Reima 110, ehjä",
    body: "Kasvettu yli — vetoketju toimii, taskut ehjät, vain pari pientä jälkeä rinnuksessa. Nouto eteisestä, en lähetä.",
    author: "Sanna R.", authorFull: "Sanna Räsänen",
    address: "Toinen linja 14", neighborhood: "Kallio",
    time: "3 t", precise: "klo 11:30",
    avatar: "https://i.pravatar.cc/120?img=47",
    image: "https://images.unsplash.com/photo-1551803091-e20673f15770?w=900&q=85&auto=format",
    likes: 9, saves: 3,
    distance: "230 m",
    verified: true,
  },
  {
    id: "p6", type: "tarjoan",
    title: "Vien koirasi lenkille kun olet töissä",
    body: "Olen opettaja, vapaalla 14–16 ma–to. Hoidan rauhalliset isommat koirat, ei aggressiivisia. Refernssejä saa kysyä.",
    author: "Liisa M.", authorFull: "Liisa Mäkelä",
    address: "Sörnäisten rantatie 13", neighborhood: "Hakaniemi",
    time: "4 t", precise: "klo 10:45",
    avatar: "https://i.pravatar.cc/120?img=44",
    price: "10 € / h",
    likes: 22, saves: 14,
    distance: "1.1 km",
    online: true, verified: true,
    rating: 4.8, reviews: 19,
  },
  {
    id: "p7", type: "tarjoan",
    title: "IKEA Malm-sänky 140cm + patja, hyvässä kunnossa",
    body: "Muutto pakottaa myymään. Patja Hövåg on n. 3v vanha, vain yhdellä omistajalla, peittolakanat aina.",
    author: "Pekka R.", authorFull: "Pekka Rantanen",
    address: "Kustaankatu 4", neighborhood: "Kallio",
    time: "5 t", precise: "klo 09:42",
    avatar: "https://i.pravatar.cc/120?img=64",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=85&auto=format",
    price: "120 €",
    likes: 7,
    distance: "180 m",
    verified: false,
  },
  {
    id: "p8", type: "tapahtuma",
    title: "Yhteislaulutilaisuus Sörkän kirjastolla",
    body: "Vanhat ikivihreät + uudempaa, säestys piano. Maksuton, kahvi & pulla 3€.",
    author: "Sörkän kirjasto", authorFull: "Helsingin kaupunginkirjasto",
    address: "Säästöpankinranta 6", neighborhood: "Sörnäinen",
    eventDate: "TI 7.5.",
    eventTime: "18:30 – 20:00",
    time: "8 t",
    avatar: null,
    attending: 12, capacity: 30,
    organizer: true,
  },
  {
    id: "p9", type: "tarvitsen",
    title: "Kuka olisi valmis vaihtamaan parkkipaikkaa?",
    body: "Minulla parkki Hämeentiellä, tarvitsisin jonkun lähempänä Vallilaa. Pitkäaikainen vaihto ok, kompensoin tarvittaessa.",
    author: "Aki H.", authorFull: "Aki Hakala",
    address: "Hämeentie 50", neighborhood: "Kallio",
    time: "11 t", precise: "eilen 22:14",
    avatar: "https://i.pravatar.cc/120?img=68",
    likes: 2,
    distance: "470 m",
  },
  {
    id: "p10", type: "lainaa",
    title: "Vaahtopesuri Kärcher SE 4001",
    body: "Tehokas matonpesuri, mukana hartsi-aine ja suuttimet. Itse käytin viime kuussa, toimi mainiosti.",
    author: "Jari P.", authorFull: "Jari Pekkanen",
    address: "Mäkelänkatu 56", neighborhood: "Vallila",
    time: "1 pv", precise: "eilen 16:00",
    avatar: "https://i.pravatar.cc/120?img=11",
    image: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=900&q=85&auto=format",
    price: "15 € / pv",
    deposit: "50 € vakuus",
    likes: 14, saves: 6,
    distance: "1.4 km",
    verified: true,
  },
  {
    id: "p11", type: "ilmaista",
    title: "Kirjat — suomalainen kaunokirjallisuus, ~30 kpl",
    body: "Kotini hyllyt täynnä, lähden Lappiin. Ota kaikki tai osa. Joukossa Tiainen, Hassinen, Kettu, Westö.",
    author: "Marja T.", authorFull: "Marja Tikkanen",
    address: "Kolmas linja 24", neighborhood: "Kallio",
    time: "1 pv",
    avatar: "https://i.pravatar.cc/120?img=43",
    likes: 6,
    distance: "300 m",
  },
  {
    id: "p12", type: "tarjoan",
    title: "Akustinen kitara Yamaha F310 + laukku",
    body: "Aloittelijan kitara, vaihdoin sähköön. Kunto hyvä, soittokunnossa, kielet vaihdettu syksyllä.",
    author: "Janne S.", authorFull: "Janne Salminen",
    address: "Porvoonkatu 11", neighborhood: "Kallio",
    time: "1 pv", precise: "eilen 13:20",
    avatar: "https://i.pravatar.cc/120?img=14",
    image: "https://images.unsplash.com/photo-1510915361894-db8b7855a8a5?w=900&q=85&auto=format",
    price: "60 €",
    likes: 12, saves: 5,
    distance: "650 m",
    verified: true,
  },
];

// Building / neighborhood meta
const BUILDING = {
  name: "As Oy Vaasankatu 14",
  shortName: "Vaasankatu 14",
  apartments: 28,
  neighbors: 11,
  newThisWeek: 3,
};

const NEIGHBORHOOD = {
  name: "Kallio",
  area: "Helsinki",
  online: 47,
  weeklyPosts: 84,
  trustScore: 4.8,
};

Object.assign(window, { POSTS_V3, BUILDING, NEIGHBORHOOD });
